<?xml version="1.0"?>
<robot name="table"
       xmlns:xi="http://www.w3.org/2001/XInclude"
       xmlns:gazebo="http://playerstage.sourceforge.net/gazebo/xmlschema/#gz"
       xmlns:model="http://playerstage.sourceforge.net/gazebo/xmlschema/#model"
       xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
       xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
       xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#joint"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:rendering="http://playerstage.sourceforge.net/gazebo/xmlschema/#rendering"
       xmlns:renderable="http://playerstage.sourceforge.net/gazebo/xmlschema/#renderable"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:physics="http://playerstage.sourceforge.net/gazebo/xmlschema/#physics">

  <property name="table_height" value="0.77" />
  <property name="table_width"  value="1.6" />
  <property name="table_depth"  value="0.8" />
  <property name="leg_radius"   value="0.02" />
  <property name="table_x"      value="0.0" />
  <property name="table_y"      value="0.0" />
  <property name="table_z"      value="0.0" />

  <property name="table_top_thickness" value="0.05"/>

  <property name="table_top_color" value="100 100 100 1" />
  <property name="leg_color" value="0 0 0 1" />

  <property name="M_PI" value="3.1415926535897931" />

  <macro name="robot_dep_table" params="parent name *origin">

    <joint name="${parent}_${name}_joint" type="fixed">
      <insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="${name}_table_top_link"/>
    </joint>


  <!-- tabletop height is .55+.01+.025=.585 -->
  <link name="${name}_table_top_link">
    <inertial>
      <mass value="1.0" />
      <origin xyz="${table_x} ${table_y} ${table_z+table_height-table_top_thickness/2}" />
      <inertia ixx="1" ixy="0"  ixz="0"
               iyy="1" iyz="0"
               izz="1" />
    </inertial> 
    <visual>
      <origin xyz="${table_x} ${table_y} ${table_z+table_height-table_top_thickness/2}" />
      <geometry>
        <box size="${table_width} ${table_depth} ${table_top_thickness}" />
      </geometry>
      <material name="table_top_grey">
        <color rgba="${table_top_color}"/>
      </material>
    </visual> 
    <collision>
      <origin xyz="${table_x} ${table_y} ${table_z+table_height-table_top_thickness/2}" />
      <geometry>
        <box size="${table_width} ${table_depth} ${table_top_thickness}" />
      </geometry>
    </collision>
  </link>

  <joint name="${name}_leg1_joint" type="fixed" >
    <parent link="${name}_table_top_link" />
    <origin xyz="${table_x+table_width/2} ${table_y+table_depth/2} ${table_z+table_height}" rpy="0 0 0" />
    <child link="${name}_leg1_link" />
  </joint> 
  <link name="${name}_leg1_link">
    <inertial>
      <mass value="1.0" />
      <origin xyz="0 0 ${-table_height/2}" />
      <inertia ixx="0.1" ixy="0"  ixz="0"
               iyy="0.1" iyz="0"
               izz="0.01" />
    </inertial> 
    <visual>
      <origin xyz="0.0 0.0 ${-table_height/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${leg_radius}" length="${table_height}" />
      </geometry>
      <material name="leg1_black">
        <color rgba="${leg_color}"/>
      </material>
    </visual> 
    <collision>
      <origin xyz="0.0 0.0 ${-table_height/2}" rpy="0.0 0.0 0.0" />
      <geometry>
        <cylinder radius="${leg_radius}" length="${table_height}" />
      </geometry>
    </collision>
  </link>

  <joint name="${name}_leg2_joint" type="fixed" >
    <parent link="${name}_table_top_link" />
    <origin xyz="${table_x-table_width/2} ${table_y+table_depth/2} ${table_z+table_height}" rpy="0 0 0" />
    <child link="${name}_leg2_link" />
  </joint> 
  <link name="${name}_leg2_link">
    <inertial>
      <mass value="1.0" />
      <origin xyz="0 0 ${-table_height/2}" />
      <inertia ixx="0.1" ixy="0"  ixz="0"
               iyy="0.1" iyz="0"
               izz="0.01" />
    </inertial> 
    <visual>
      <origin xyz="0.0 0.0 ${-table_height/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${leg_radius}" length="${table_height}" />
      </geometry>
      <material name="leg2_black">
        <color rgba="${leg_color}"/>
      </material>
    </visual> 
    <collision>
      <origin xyz="0.0 0.0 ${-table_height/2}" rpy="0.0 0.0 0.0" />
      <geometry>
        <cylinder radius="${leg_radius}" length="${table_height}" />
      </geometry>
    </collision>
  </link>

  <joint name="${name}_leg3_joint" type="fixed" >
    <parent link="${name}_table_top_link" />
    <origin xyz="${table_x+table_width/2} ${table_y-table_depth/2} ${table_z+table_height}" rpy="0 0 0" />
    <child link="${name}_leg3_link" />
  </joint> 
  <link name="${name}_leg3_link">
    <inertial>
      <mass value="1.0" />
      <origin xyz="0 0 ${-table_height/2}" />
      <inertia ixx="0.1" ixy="0"  ixz="0"
               iyy="0.1" iyz="0"
               izz="0.01" />
    </inertial> 
    <visual>
      <origin xyz="0.0 0.0 ${-table_height/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${leg_radius}" length="${table_height}" />
      </geometry>
      <material name="leg3_black">
        <color rgba="${leg_color}"/>
      </material>
    </visual> 
    <collision>
      <origin xyz="0.0 0.0 ${-table_height/2}" rpy="0.0 0.0 0.0" />
      <geometry>
        <cylinder radius="${leg_radius}" length="${table_height}" />
      </geometry>
    </collision>
  </link>

  <joint name="${name}_leg4_joint" type="fixed" >
    <parent link="${name}_table_top_link" />
    <origin xyz="${table_x-table_width/2} ${table_y-table_depth/2} ${table_z+table_height}" rpy="0 0 0" />
    <child link="${name}_leg4_link" />
  </joint> 
  <link name="${name}_leg4_link">
    <inertial>
      <mass value="1.0" />
      <origin xyz="0 0 ${-table_height/2}" />
      <inertia ixx="0.1" ixy="0"  ixz="0"
               iyy="0.1" iyz="0"
               izz="0.01" />
    </inertial> 
    <visual>
      <origin xyz="0.0 0.0 ${-table_height/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${leg_radius}" length="${table_height}" />
      </geometry>
      <material name="leg4_black">
        <color rgba="${leg_color}"/>
      </material>
    </visual> 
    <collision>
      <origin xyz="0.0 0.0 ${-table_height/2}" rpy="0.0 0.0 0.0" />
      <geometry>
        <cylinder radius="${leg_radius}" length="${table_height}" />
      </geometry>
    </collision>
  </link>
  </macro>
</robot>